"""Export service: MikroTik ZIP bundle and QR poster generation."""

import io
import zipfile
import json
from pathlib import Path
from typing import Optional

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"


def generate_mikrotik_zip(
    portal_config: dict,
    brand_name: str,
    slug: str,
    logo_b64: str | None = None,
    background_b64: str | None = None,
) -> io.BytesIO:
    buf = io.BytesIO()
    template_id = portal_config.get("template_id", "spotlight")
    theme = portal_config.get("theme", {})
    typography = portal_config.get("typography", {})
    brand = portal_config.get("brand", {})
    card = portal_config.get("card", {})
    components = portal_config.get("components", {})
    animations = portal_config.get("animations", {})

    base_template = _get_base_template_file(template_id)
    base_html = ""
    if base_template and base_template.exists():
        base_html = base_template.read_text(encoding="utf-8")

    portal_url = f"https://portal.honestbill.co.ke/portal/{slug}"

    inline_css = _generate_inline_css(theme, typography, card, animations)
    inline_js = _generate_inline_js(components, animations, portal_url)

    if "{{" in base_html or "{%" in base_html:
        html = base_html
    else:
        html = _build_standalone_html(base_html, brand, inline_css, inline_js, portal_url)

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("index.html", html)
        zf.writestr("style.css", inline_css)
        zf.writestr("script.js", inline_js)
        zf.writestr("portal_config.json", json.dumps(portal_config, indent=2))

        if logo_b64:
            import base64
            try:
                logo_data = base64.b64decode(logo_b64)
                zf.writestr("images/logo.png", logo_data)
            except Exception:
                pass

        if background_b64:
            import base64
            try:
                bg_data = base64.b64decode(background_b64)
                zf.writestr("images/background.png", bg_data)
            except Exception:
                pass

        readme = f"""=== {brand_name} Portal Offline Package ===

Deploy to MikroTik:
1. Open WinBox
2. Navigate to Files
3. Drag this ZIP onto the router
4. Extract (Files > Extract)
5. Set hotspot login page to index.html

Portal URL (online): {portal_url}

Generated by HonestBill Portal Studio
"""
        zf.writestr("README.txt", readme)

    buf.seek(0)
    return buf


def _get_base_template_file(template_id: str) -> Path | None:
    mapping = {
        "executive-dark": "portal_dashboard.html",
        "executive-light": "portal_dashboard.html",
        "premium-hotel": "portal_spotlight.html",
        "modern-isp": "portal_dashboard.html",
        "corporate-blue": "portal_dashboard.html",
        "gaming-neon": "portal_spotlight.html",
        "cyberpunk": "portal_dashboard.html",
        "streaming-portal": "portal_dashboard.html",
        "rgb-wave": "portal_spotlight.html",
        "glass-morphism": "portal_dashboard.html",
        "apple-style": "portal_spotlight.html",
        "material-design": "portal_dashboard.html",
        "clean-white": "portal_spotlight.html",
        "kenyan-gold": "portal_dashboard.html",
        "safari": "portal_spotlight.html",
        "afro-modern": "portal_spotlight.html",
        "nairobi-night": "portal_dashboard.html",
        "sunset-vibes": "portal_spotlight.html",
        "ocean-deep": "portal_dashboard.html",
        "midnight-purple": "portal_bento.html",
        "coffee-shop": "portal_spotlight.html",
        "cherry-blossom": "portal_dashboard.html",
        "split-modern": "portal_split.html",
        "split-ocean": "portal_split.html",
        "split-sunset": "portal_split.html",
        "split-forest": "portal_split.html",
        "bento-modern": "portal_bento.html",
        "bento-neon": "portal_bento.html",
        "bento-warm": "portal_bento.html",
    }
    filename = mapping.get(template_id, "portal_spotlight.html")
    return TEMPLATES_DIR / filename


def _build_standalone_html(base_html: str, brand: dict, css: str, js: str, portal_url: str) -> str:
    brand_name = brand.get("name", "WiFi Portal")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{brand_name} - WiFi Portal</title>
<style>{css}</style>
</head>
<body>
<div id="portal-root">
<div class="portal-container">
  <div class="portal-header">
    <div class="portal-brand">
      <span class="portal-emoji">{brand.get("emoji", "📶")}</span>
      <h1 class="portal-name">{brand_name}</h1>
    </div>
    {f'<p class="portal-tagline">{brand.get("tagline", "")}</p>' if brand.get("tagline") else ""}
    {f'<p class="portal-location">{brand.get("location", "")}</p>' if brand.get("location") else ""}
  </div>
  <div class="packages-container">
    <p class="packages-placeholder">Packages will load from the live portal.</p>
  </div>
  <div class="portal-footer">
    <a href="{portal_url}" class="portal-link">Open Live Portal</a>
  </div>
</div>
</div>
<script>{js}</script>
</body>
</html>"""


def _generate_inline_css(theme: dict, typography: dict, card: dict, animations: dict) -> str:
    primary = theme.get("primary_color", "#E8B84B")
    secondary = theme.get("secondary_color", "#1a1a2e")
    accent = theme.get("accent_color", "#00d4aa")
    bg_value = theme.get("background_value", "#0a0a0a")
    bg_type = theme.get("background_type", "solid")
    gradient = theme.get("gradient", "")
    overlay = theme.get("overlay_color", "#000000")
    overlay_opacity = theme.get("overlay_opacity", 0.3)
    button_style = theme.get("button_style", "rounded")

    ff = typography.get("font_family", "Inter")
    heading_size = typography.get("heading_size", 32)
    body_size = typography.get("body_size", 15)
    font_weight = typography.get("font_weight", 500)
    letter_spacing = typography.get("letter_spacing", 0.3)

    card_style = card.get("style", "glass")
    card_radius = card.get("radius", 12)

    btn_radius = {"rounded": "12px", "pill": "24px", "sharp": "0px"}.get(button_style, "12px")

    bg_css = f"background: {bg_value};"
    if bg_type == "gradient" and gradient:
        bg_css = f"background: {gradient};"
    if bg_type in ("image", "video"):
        bg_css = "background: #000;"

    entrance = animations.get("entrance", "fade-in")
    anim_css = ""
    if entrance == "slide-up":
        anim_css = "@keyframes slideUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }"
    elif entrance == "zoom":
        anim_css = "@keyframes zoomIn { from { opacity: 0; transform: scale(0.95); } to { opacity: 1; transform: scale(1); } }"
    elif entrance == "fade-in":
        anim_css = "@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }"

    return f"""/* Portal Studio Generated Styles */
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ {bg_css} color: #fff; font-family: '{ff}', sans-serif; font-size: {body_size}px; font-weight: {font_weight}; letter-spacing: {letter_spacing}px; min-height: 100vh; }}
.portal-root {{ position: relative; min-height: 100vh; }}
.portal-overlay {{ position: fixed; inset: 0; background: {overlay}; opacity: {overlay_opacity}; pointer-events: none; z-index: 0; }}
.portal-container {{ position: relative; z-index: 1; max-width: 480px; margin: 0 auto; padding: 40px 20px; animation: fadeIn 0.6s ease-out; }}
{anim_css}
.portal-header {{ text-align: center; margin-bottom: 40px; }}
.portal-emoji {{ font-size: 48px; display: block; margin-bottom: 12px; }}
.portal-name {{ font-size: {heading_size}px; font-weight: {font_weight + 100}; color: {primary}; margin-bottom: 8px; }}
.portal-tagline {{ font-size: {body_size}px; color: rgba(255,255,255,0.7); margin-bottom: 4px; }}
.portal-location {{ font-size: {body_size - 2}px; color: rgba(255,255,255,0.5); }}
.packages-container {{ margin: 30px 0; }}
.portal-footer {{ text-align: center; margin-top: 40px; padding: 20px; }}
.portal-link {{ display: inline-block; padding: 12px 24px; background: {primary}; color: #000; border-radius: {btn_radius}; text-decoration: none; font-weight: 600; }}
.packages-placeholder {{ text-align: center; color: rgba(255,255,255,0.4); font-style: italic; }}
h1, h2, h3 {{ font-family: '{ff}', sans-serif; }}
"""


def _generate_inline_js(components: dict, animations: dict, portal_url: str) -> str:
    return f"""// Portal Studio Generated
(function() {{
    var root = document.getElementById('portal-root');
    if (root) {{
        root.classList.add('portal-root');
        var overlay = document.createElement('div');
        overlay.className = 'portal-overlay';
        root.prepend(overlay);
    }}
    console.log('HonestBill Portal v2 | Live: {portal_url}');
}})();
"""


def generate_qr_poster_html(portal_config: dict, brand_name: str, slug: str) -> str:
    theme = portal_config.get("theme", {})
    brand = portal_config.get("brand", {})
    primary = theme.get("primary_color", "#E8B84B")
    secondary = theme.get("secondary_color", "#1a1a2e")
    bg_value = theme.get("background_value", "#0a0a0a")
    ff = theme.get("typography", {}).get("font_family", "Inter")
    portal_url = f"https://portal.honestbill.co.ke/portal/{slug}"
    tagline = brand.get("tagline", "Free WiFi")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>QR Poster - {brand_name}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family={ff.replace(' ', '+')}:wght@400;600;700&display=swap');
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: {secondary}; color: #fff; font-family: '{ff}', sans-serif; min-height: 100vh; display: flex; align-items: center; justify-content: center; }}
  .poster {{ width: 400px; padding: 40px; background: {bg_value}; border-radius: 24px; text-align: center; border: 1px solid {primary}33; }}
  .emoji {{ font-size: 64px; margin-bottom: 16px; }}
  h1 {{ font-size: 32px; color: {primary}; margin-bottom: 8px; }}
  p {{ color: rgba(255,255,255,0.7); margin-bottom: 24px; }}
  .qr-placeholder {{ width: 200px; height: 200px; margin: 0 auto 24px; background: #fff; border-radius: 16px; display: flex; align-items: center; justify-content: center; font-size: 14px; color: #999; }}
  .steps {{ text-align: left; background: rgba(255,255,255,0.05); border-radius: 12px; padding: 16px; margin-bottom: 20px; }}
  .steps li {{ padding: 4px 0; font-size: 14px; color: rgba(255,255,255,0.8); }}
  .url {{ font-size: 12px; color: {primary}; word-break: break-all; }}
</style>
</head>
<body>
<div class="poster">
  <div class="emoji">{brand.get("emoji", "📶")}</div>
  <h1>{brand_name}</h1>
  <p>{tagline}</p>
  <div class="qr-placeholder">QR Code<br>(Print Ready)</div>
  <p style="font-size:12px;color:rgba(255,255,255,0.4)">Scan to connect</p>
  <ol class="steps">
    <li>1. Open your camera</li>
    <li>2. Scan the QR code</li>
    <li>3. Select a package</li>
    <li>4. Pay &amp; connect</li>
  </ol>
  <div class="url">{portal_url}</div>
</div>
</body>
</html>"""
