"""Add Phase 3 session fields

Revision ID: 2d3b8db79780
Revises: 5a510c6964e6
Create Date: 2026-05-27 04:11:38.872790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d3b8db79780'
down_revision: Union[str, None] = '5a510c6964e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invite_tokens_email', table_name='invite_tokens')
    op.drop_index('ix_invite_tokens_token', table_name='invite_tokens')
    op.drop_table('invite_tokens')
    op.add_column('sessions', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('disconnected_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('mikrotik_user_id', sa.String(length=128), nullable=True))
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=15),
               nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'EXPIRED', 'FAILED', 'REVOKED', name='sessionstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('sessions', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sessions', 'reconnect_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index('ix_sessions_checkout_request_id', table_name='sessions')
    op.drop_index('ix_sessions_reconnect_code', table_name='sessions')
    op.drop_index('ix_sessions_status', table_name='sessions')
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_unique_constraint(None, 'sessions', ['reconnect_code'])
    op.drop_constraint('sessions_tenant_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('sessions', 'phone_number')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'checkout_request_id')
    op.alter_column('tenants', 'portal_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'portal_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('sessions', sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_tenant_id_fkey', 'sessions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.create_index('ix_sessions_status', 'sessions', ['status'], unique=False)
    op.create_index('ix_sessions_reconnect_code', 'sessions', ['reconnect_code'], unique=True)
    op.create_index('ix_sessions_checkout_request_id', 'sessions', ['checkout_request_id'], unique=False)
    op.alter_column('sessions', 'reconnect_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('sessions', 'last_seen_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'EXPIRED', 'FAILED', 'REVOKED', name='sessionstatus'),
               existing_nullable=False)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_column('sessions', 'mikrotik_user_id')
    op.drop_column('sessions', 'disconnected_at')
    op.drop_column('sessions', 'activated_at')
    op.create_table('invite_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='invite_tokens_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invite_tokens_pkey')
    )
    op.create_index('ix_invite_tokens_token', 'invite_tokens', ['token'], unique=True)
    op.create_index('ix_invite_tokens_email', 'invite_tokens', ['email'], unique=False)
    # ### end Alembic commands ###
