"""add reconnect_code and last_seen_at to sessions

Revision ID: 585ffe3c1ef7
Revises: bc8d4882cdab
Create Date: 2026-05-14 21:49:12.966426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585ffe3c1ef7'
down_revision: Union[str, None] = 'bc8d4882cdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
