"""add_portal_config_and_onboarding_complete

Revision ID: 918901223057
Revises: e5fd6f4909cd
Create Date: 2026-05-20 11:08:13.044790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918901223057'
down_revision: Union[str, None] = 'e5fd6f4909cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
