"""add reconnect_code and last_seen_at to sessions

Revision ID: bc8d4882cdab
Revises: 088243f848ea
Create Date: 2026-05-14 21:48:25.667742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8d4882cdab'
down_revision: Union[str, None] = '088243f848ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('reconnect_code', sa.String(length=10), nullable=True))
    op.add_column('sessions', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sessions_reconnect_code'), 'sessions', ['reconnect_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_reconnect_code'), table_name='sessions')
    op.drop_column('sessions', 'last_seen_at')
    op.drop_column('sessions', 'reconnect_code')
    # ### end Alembic commands ###
