"""fix_invitestatus_enum

Revision ID: dfb499af46bb
Revises: a1b2c3d4e5f6
Create Date: 2026-05-20 10:05:12.031571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfb499af46bb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.alter_column('admin_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('admin_users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('isp_invites_token_key'), 'isp_invites', type_='unique')
    op.drop_index(op.f('ix_isp_invites_token'), table_name='isp_invites')
    op.create_index(op.f('ix_isp_invites_token'), 'isp_invites', ['token'], unique=True)
    op.create_index(op.f('ix_isp_invites_created_by'), 'isp_invites', ['created_by'], unique=False)
    op.create_index(op.f('ix_isp_invites_expires_at'), 'isp_invites', ['expires_at'], unique=False)
    op.create_unique_constraint('uq_isp_invites_token', 'isp_invites', ['token'])
    op.drop_constraint(op.f('isp_invites_used_by_tenant_id_fkey'), 'isp_invites', type_='foreignkey')
    op.drop_column('isp_invites', 'note')
    op.drop_column('isp_invites', 'used_by_tenant_id')
    op.drop_column('isp_invites', 'used_at')
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tenants', 'commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=4, scale=3),
               existing_nullable=False)
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('tenants', 'commission_rate',
               existing_type=sa.Numeric(precision=4, scale=3),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tenants', 'slug',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('isp_invites', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('isp_invites', sa.Column('used_by_tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('isp_invites', sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('isp_invites_used_by_tenant_id_fkey'), 'isp_invites', 'tenants', ['used_by_tenant_id'], ['id'])
    op.drop_constraint('uq_isp_invites_token', 'isp_invites', type_='unique')
    op.drop_index(op.f('ix_isp_invites_expires_at'), table_name='isp_invites')
    op.drop_index(op.f('ix_isp_invites_created_by'), table_name='isp_invites')
    op.drop_index(op.f('ix_isp_invites_token'), table_name='isp_invites')
    op.create_index(op.f('ix_isp_invites_token'), 'isp_invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('isp_invites_token_key'), 'isp_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('admin_users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('admin_users', 'hashed_password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('admin_users', 'email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
