"""add_portal_config_and_onboarding_complete

Revision ID: e5fd6f4909cd
Revises: dfb499af46bb
Create Date: 2026-05-20 11:04:28.080751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5fd6f4909cd'
down_revision: Union[str, None] = 'dfb499af46bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('portal_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'portal_config')
    # ### end Alembic commands ###
