export interface TourStep {
  id: string
  title: string
  description: string
  selector?: string
  position?: 'top' | 'bottom' | 'left' | 'right'
  section?: string
  url?: string
}

export const tourSteps: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to WiBill',
    description: 'This tour walks you through every feature — including the ones that aren\'t immediately obvious. Use Next/Back or arrow keys to navigate.',
    section: 'Overview',
  },
  {
    id: 'sidebar-collapse',
    title: 'Collapse the Sidebar',
    description: 'Click the chevron (top-right of sidebar) to collapse it into icons only. Useful for more screen space on smaller monitors. Hover any icon to see its label.',
    selector: '.desktop-sidebar button',
    position: 'right',
    section: 'Overview',
  },
  {
    id: 'sidebar-live-card',
    title: 'Live Data Card',
    description: 'At the bottom of the sidebar you\'ll see your ISP name, today\'s revenue, and active session count — all live-updating. Click the WiBill logo to open your customer portal.',
    selector: '.desktop-sidebar',
    position: 'right',
    section: 'Overview',
  },
  {
    id: 'nav-session-badge',
    title: 'Live Session Count',
    description: 'The Sessions nav item shows a live badge with how many users are currently online. Notifications also show an unread badge when you have new alerts.',
    selector: '[data-nav="/dashboard/sessions"]',
    position: 'right',
    section: 'Overview',
  },
  {
    id: 'dashboard-overview',
    title: 'Dashboard Overview',
    description: 'Your main page shows today\'s revenue, a weekly cash flow chart (gold bar = today), live sessions, and recent payments. Click any card row to drill into details.',
    selector: '[data-nav="/dashboard"]',
    position: 'right',
    url: '/dashboard',
    section: 'Dashboard',
  },
  {
    id: 'quick-actions',
    title: 'Quick Actions',
    description: 'Below the main panels you\'ll find quick action buttons — Setup Hotspot, Add Voucher, Customize Portal, Send SMS. Items with gold borders need your attention.',
    url: '/dashboard',
    section: 'Dashboard',
  },
  {
    id: 'network-page',
    title: 'Network Monitoring',
    description: 'Navigate here to see router health, last sync time, connected devices, and bandwidth usage. If "Last Poll" shows a recent time, your router is communicating with WiBill.',
    selector: '[data-nav="/dashboard/network"]',
    position: 'right',
    url: '/dashboard/network',
    section: 'Network',
  },
  {
    id: 'sessions-page',
    title: 'Sessions — Manage Users',
    description: 'Click any session row to open the detail drawer. From there you can Extend time, Suspend access, Disconnect a user, or see their full data usage history.',
    selector: '[data-nav="/dashboard/sessions"]',
    position: 'right',
    url: '/dashboard/sessions',
    section: 'Sessions',
  },
  {
    id: 'vouchers-context-menu',
    title: 'Voucher Right-Click Menu',
    description: 'On the Vouchers page, right-click (or long-press on mobile) any individual voucher code to Copy it, Void it, or View its usage history. This is the fastest way to manage single codes.',
    selector: '[data-nav="/dashboard/vouchers"]',
    position: 'right',
    url: '/dashboard/vouchers',
    section: 'Vouchers',
  },
  {
    id: 'vouchers-select-mode',
    title: 'Voucher Bulk Select',
    description: 'Click "Select" (top-right of vouchers table) to enter bulk mode. Check individual codes or use "Select All Unused" to batch Copy or Void multiple vouchers at once.',
    url: '/dashboard/vouchers',
    section: 'Vouchers',
  },
  {
    id: 'vouchers-generate',
    title: 'Generate Vouchers',
    description: 'Click "Generate" to create a batch. You can set duration, count, and optionally link vouchers to a package (which sets price and speed limits automatically).',
    url: '/dashboard/vouchers',
    section: 'Vouchers',
  },
  {
    id: 'vouchers-batch-labels',
    title: 'Batch Grouping',
    description: 'Vouchers are grouped by duration + creation date (e.g. "1 hour · Aug 19"). Each batch has its own Copy All and Void All actions. Expand/collapse batches with the chevron.',
    url: '/dashboard/vouchers',
    section: 'Vouchers',
  },
  {
    id: 'transactions-filters',
    title: 'Transaction Filters',
    description: 'On the Transactions page, use the filters at the top to narrow by type (M-Pesa, voucher, manual), date range, or status. Click any row for the full audit trail.',
    selector: '[data-nav="/dashboard/transactions"]',
    position: 'right',
    url: '/dashboard/transactions',
    section: 'Transactions',
  },
  {
    id: 'packages-create',
    title: 'Packages — Pricing Tiers',
    description: 'Create packages with name, duration, price, speed limit, and data cap. Packages appear on your customer portal. Link a package to vouchers so they auto-set the price.',
    selector: '[data-nav="/dashboard/packages"]',
    position: 'right',
    url: '/dashboard/packages',
    section: 'Packages',
  },
  {
    id: 'mikrotik-config',
    title: 'MikroTik Connection',
    description: 'Enter your router\'s IP address and hotspot name here. The Bridge URL tells WiBill how to reach your router. Use "Test Connection" to verify it\'s working.',
    selector: '[data-nav="/dashboard/mikrotik"]',
    position: 'right',
    url: '/dashboard/mikrotik',
    section: 'MikroTik',
  },
  {
    id: 'mpesa-config',
    title: 'M-Pesa Payments',
    description: 'Set up Lipa na M-Pesa so customers can pay via STK push. Enter your Paybill number, consumer key/secret, and passkey. Use "Send Test STK Push" to verify.',
    selector: '[data-nav="/dashboard/mpesa"]',
    position: 'right',
    url: '/dashboard/mpesa',
    section: 'M-Pesa',
  },
  {
    id: 'portal-design',
    title: 'Portal Design',
    description: 'Customize what your customers see when they connect to WiFi. Choose a template (Dashboard, Bento, Spotlight, Split), upload your logo and sticker image, and set brand colors. The live preview updates as you edit.',
    selector: '[data-nav="/dashboard/wizard"]',
    position: 'right',
    url: '/dashboard/wizard',
    section: 'Portal Design',
  },
  {
    id: 'portal-logo',
    title: 'Logo & Sticker Upload',
    description: 'In Portal Design, click "Upload logo" to add your ISP brand logo. Click "Choose image" under Sticker to upload a background/photo. Both save automatically when you click Save.',
    url: '/dashboard/wizard',
    section: 'Portal Design',
  },
  {
    id: 'analytics',
    title: 'Analytics',
    description: 'View revenue trends, user growth, peak usage hours, and data consumption patterns. Use the date range picker to compare periods.',
    selector: '[data-nav="/dashboard/analytics"]',
    position: 'right',
    url: '/dashboard/analytics',
    section: 'Analytics',
  },
  {
    id: 'sms-page',
    title: 'Bulk SMS',
    description: 'Send promotional or notification messages to your users. Compose a message, select recipients (all, active, expired), and send immediately or schedule for later.',
    selector: '[data-nav="/dashboard/comms"]',
    position: 'right',
    url: '/dashboard/comms',
    section: 'SMS',
  },
  {
    id: 'loyalty-page',
    title: 'Loyalty & Rewards',
    description: 'Configure reward tokens and points system. Users earn points per session which they can redeem for free hours. Enable/disable the loyalty program from here.',
    selector: '[data-nav="/dashboard/loyalty"]',
    position: 'right',
    url: '/dashboard/loyalty',
    section: 'Loyalty',
  },
  {
    id: 'notifications-page',
    title: 'Notifications',
    description: 'All system alerts appear here — payment confirmations, session expirations, router disconnections. Unread notifications show a badge on the sidebar.',
    selector: '[data-nav="/dashboard/notifications"]',
    position: 'right',
    url: '/dashboard/notifications',
    section: 'Notifications',
  },
  {
    id: 'settings-page',
    title: 'Settings',
    description: 'Manage your ISP name, email, portal URL, and notification preferences. You can also change your password and manage team access from here.',
    selector: '[data-nav="/dashboard/settings"]',
    position: 'right',
    url: '/dashboard/settings',
    section: 'Settings',
  },
  {
    id: 'hotspots-page',
    title: 'Hotspots',
    description: 'Manage multiple hotspot locations. Each hotspot gets its own portal design, packages, and session tracking. Add a new hotspot to expand to a second location.',
    selector: '[data-nav="/dashboard/hotspots"]',
    position: 'right',
    url: '/dashboard/hotspots',
    section: 'Hotspots',
  },
  {
    id: 'finish',
    title: 'You\'re All Set',
    description: 'That covers every feature. Click Support in the sidebar anytime to replay this tour. For help, email support@honestbill.co.ke',
    section: 'Done',
  },
]
